### ISSUE TITLE
DEDGE is broken

### ISSUE THREAD

**Issue by leptun** [wavexx/Prusa-Firmware#3]
Hi wavexx.

As the title says DEDGE is currently kinda broken. The problem is sm4.h/c was not updated to DEDGE and XYZ calibration doesn't work. As for the normal dedge stepping, I don't like how there still is the 1us delay after the step. Is this required? I feel that with dedge we can achieve faster speeds without jerking, but I think it's limited by delays like this. What do you think?

**Comment by wavexx** [comment]
Missed this entirely, turns out I wasn't watching my own repo...
I'll have a look at sm4 now.

As for the delay, which one are you referring to?

There is still a minimum delay required between each edge, but even a nop should be long enough. I didn't optimize all cases though. The code in tmc2130.cpp is only used for maintenance, so I didn't want to ifdef each single call.

All the cases in stepper.cpp though should be free of delays (well, except the unused/broken backlash code).

**Comment by leptun** [comment]
It is in the stepper ISR where it goes Step_high(toggle) -> delay -> Step_low(nop)

It’s not significant, but I think it would be best if it was optimized all the way. As for the necessity of delay between steps, i think there is enough delay from the code itself between steps. No need to worry about timing in this case.

I’ve reverted to LA15 without dedge in the meantime since I had to redo XYZ calibration after messing with the lcd and corrupting the eeprom.

**Comment by wavexx** [comment]
On Sat, Jul 13 2019, leptun wrote:
> It is in the stepper ISR where it goes Step_high(toggle) -> delay -> Step_low(nop)

Ok, I think you're referring to the delay of 1us in babystep(). Not
critical, as these are inserted by the lcd though Live Z, but we can
remove that.

By reshuffling the code I can probably remove the repetition, but there
are quite a few cases around. I would actually get rid of sm4 entirely,
but I tried to limit changes to make them more digestible by Prusa,
given how long it takes to get them in..

**Comment by wavexx** [comment]
I fixed sm4 which was quite trivial. I can complete a full XYZ calibration successfully.

I also improved babystep to avoid delays, but I'm afraid there are probably some cases where I made it worse. There's a minimum delay required as the driver setups a direction inversion which wasn't respected (in babystep, and several other cases I already fixed).

Removing this delay during Z live adjustment is definitely possible by changing the direction only as needed, but I need to go through all cases and check. For now I just made it correct.

**Comment by leptun** [comment]
Perfect. Will merge the changes soon. If it causes more problems than it solves, I think we should just leave it as is.

**Comment by wavexx** [comment]
There are other tweaks and cleanups to do on sm4 to avoid having constants sprinkled in 10 different places. I'd like to wait for https://github.com/prusa3d/Prusa-Firmware/pull/1263 before going on.

**Comment by leptun** [comment]
I have another approach to that on my MKP branch that doesn’t use variables, only defines. I think that is a bit superior. I made it since that change would constantly error on linker.

**Comment by wavexx** [comment]
The extra delay in babystep is now gone. I've done so by changing the logic of the isr and making sure that babysteps/liveZ cannot be inserted/changed while using sm4.

The pinda temp calibration as well as single Z probe (G30) uses a mix of sm4 and the planner via find_bed_induction_sensor_point_z(). Now that's truly ugly..
