### ISSUE TITLE
Build with platformio failed

### ISSUE THREAD

**Issue by bgiot** [wavexx/Prusa-Firmware#5]
Hi,
I have a working build process with platformio. I can successfuly build Prusa firmware 3.7.2.
But with your MK3_LA15 version, there is a issue linked to the new heatbed pwm.
Here is the error:
wiring.c.o (symbol from plugin): In function `__vector_23':
(.text+0x0): multiple definition of `__vector_23'
build/MK3-BMG-1.8/src/heatbed_pwm.cpp.o (symbol from plugin):(.text+0x0): first defined here
Any clue to fix this ?
Thanks a lot!

**Comment by leptun** [comment]
Take a look at https://github.com/prusa3d/Prusa-Firmware/issues/2027

**Comment by bgiot** [comment]
I had a look... need to figure-out how to setup a custom package/platform for platform.io...

**Comment by leptun** [comment]
You need the new board definition. Read the readme from Mk3 branch from prusa.

**Comment by bgiot** [comment]
I made the necessary PR on platformio to integrate prusa_rambo board.
https://github.com/platformio/platformio-pkg-framework-arduinoavr/pull/22
https://github.com/platformio/platform-atmelavr/pull/163

**Comment by bgiot** [comment]
A small change of code in lcd.h/lcd.cpp is needed also. 
https://community.platformio.org/t/error-when-building-latest-3d-printer-firmware/9506/16?u=ivankravets

**Comment by leptun** [comment]
What is the problem with the lcd.c/h? If it’s related to the warnings, they will be fixed in the next minor release (3.8.1).
